services:
  - type: web
    name: fzdigitals
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --log-file -
    releaseCommand: python manage.py migrate --noinput
    env: python
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: fzdigitals.onrender.com
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.14.3

databases:
  - name: fzdigitals-db
    databaseName: fzdigitals
    user: fzdigitals

crons:
  - name: keep-awake
    schedule: "*/10 * * * *"
    command: "curl https://fzdigitals.onrender.com/"
