services:
  - type: web
    name: tellermedia
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    releaseCommand: python3 manage.py migrate --no-input
