# Generated by Django 4.2.16 on 2026-08-19 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slideshow', '0003_mediafile_user_devicepairing'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_question', models.CharField(choices=[('pet', 'What was the name of your first pet?'), ('school', 'What was the name of your first school?'), ('city', 'In which city were you born?'), ('mother', "What is your mother's maiden name?"), ('job', 'What was your first job?')], max_length=50)),
                ('security_answer', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
