# Generated by Django 4.2.16 on 2026-08-23 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slideshow', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicepairing',
            name='screen',
            field=models.IntegerField(choices=[(1, 'Screen-1'), (2, 'Screen-2'), (3, 'Screen-3'), (4, 'Screen-4'), (5, 'Screen-5')], default=1),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='screen',
            field=models.IntegerField(choices=[(1, 'Screen-1'), (2, 'Screen-2'), (3, 'Screen-3'), (4, 'Screen-4'), (5, 'Screen-5')], default=1),
        ),
        migrations.AlterField(
            model_name='devicepairing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='devicepairing',
            unique_together={('user', 'screen')},
        ),
    ]
