# Generated by Django 4.2.16 on 2026-09-01 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slideshow', '0006_devicepairing_screen_mediafile_screen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicepairing',
            name='screen',
            field=models.IntegerField(choices=[(1, 'Slideshow-1'), (2, 'Slideshow-2'), (3, 'Slideshow-3'), (4, 'Slideshow-4'), (5, 'Slideshow-5')], default=1),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='screen',
            field=models.IntegerField(choices=[(1, 'Slideshow-1'), (2, 'Slideshow-2'), (3, 'Slideshow-3'), (4, 'Slideshow-4'), (5, 'Slideshow-5')], default=1),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('device_type', models.CharField(choices=[('browser', 'Browser'), ('usb', 'USB Device')], default='browser', max_length=20)),
                ('screen', models.IntegerField(choices=[(1, 'Slideshow-1'), (2, 'Slideshow-2'), (3, 'Slideshow-3'), (4, 'Slideshow-4'), (5, 'Slideshow-5')], default=1)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
