# Generated by Django 4.2.16 on 2026-09-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0007_alter_devicepairing_screen_alter_mediafile_screen_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
