# Generated by Django 4.2.16 on 2026-09-10 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0011_alter_userprofile_security_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='screen',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicepairing',
            name='screen',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='screen',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
