# Generated by Django 4.2.16 on 2026-09-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0012_remove_screen_choices_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_active_screens',
            field=models.PositiveIntegerField(default=500, help_text='Total active screens across all slideshows; 0 = unlimited'),
        ),
    ]
