# Generated by Django 4.2.16 on 2026-09-10 07:16

from django.db import migrations, models


def update_active_screen_caps(apps, schema_editor):
    UserProfile = apps.get_model('slideshow', 'UserProfile')
    UserProfile.objects.update(max_active_screens=50)


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0013_add_max_active_screens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='max_active_screens',
            field=models.PositiveIntegerField(default=50, help_text='Total active screens across all slideshows; 0 = unlimited'),
        ),
        migrations.RunPython(update_active_screen_caps, migrations.RunPython.noop),
    ]
