# Generated by Django 4.2.16 on 2026-09-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0014_set_max_active_screens_to_50'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='max_active_screens',
            field=models.PositiveIntegerField(default=50, editable=False, help_text='Total active screens across all slideshows; 0 = unlimited'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_screens_per_slideshow',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Max devices per slideshow; 0 = unlimited'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_slideshows',
            field=models.PositiveIntegerField(default=5, help_text='Number of screens this user is allowed. This also sets the max slideshows and total active screen limit.', verbose_name='Number of screens'),
        ),
    ]
