# Generated by Django 4.2.16 on 2026-09-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0016_mosque_userprofile_vertical_mosqueslide_prayertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='max_active_screens',
            field=models.PositiveIntegerField(default=50, help_text='Upper limit of total active screens for this user. 0 = unlimited.', verbose_name='Number of screens'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_slideshows',
            field=models.PositiveIntegerField(default=5, help_text='Number of slideshows this user is allowed.', verbose_name='Number of slideshows'),
        ),
    ]
