# Generated by Django 4.2.16 on 2026-09-16 10:20

from django.db import migrations, models
from django.db.models import F


def set_number_of_screens(apps, schema_editor):
    UserProfile = apps.get_model('slideshow', 'UserProfile')
    UserProfile.objects.update(
        number_of_screens=F('max_slideshows'),
        max_active_screens=F('max_slideshows'),
        max_screens_per_slideshow=F('max_slideshows'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0017_alter_userprofile_max_active_screens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number_of_screens',
            field=models.PositiveIntegerField(default=5, help_text='Upper limit of live screens this user is allowed.', verbose_name='Number of screens'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_active_screens',
            field=models.PositiveIntegerField(default=50, editable=False, help_text='Total active screens across all slideshows; 0 = unlimited'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_slideshows',
            field=models.PositiveIntegerField(default=5, help_text='Number of slideshows (screen slots) to display in the dashboard.', verbose_name='Number of slideshows'),
        ),
        migrations.RunPython(
            code=set_number_of_screens,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
