# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0018_userprofile_number_of_screens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayertime',
            name='sunset',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
