# Generated by Django 4.2.16 on 2026-10-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0029_prayertimeoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayertime',
            name='maghrib_sunset_minutes',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minutes after sunset to set Maghrib (1-60) when maghrib_after_sunset is on.'),
        ),
        migrations.AddField(
            model_name='prayertimeoverride',
            name='maghrib_sunset_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='NULL = inherit from synced row; set = override.', null=True),
        ),
        migrations.AlterField(
            model_name='prayertimeoverride',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
