# Generated by Django 4.2.16 on 2026-10-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0030_prayertime_maghrib_sunset_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='sync_failures',
            field=models.PositiveSmallIntegerField(default=0, help_text='Consecutive sync failures since the last success; hourly retries stop after 3 until the next daily sync window.'),
        ),
    ]
